### ISSUE TITLE
Original SAM

### ISSUE THREAD

**Issue by NanoAB86** [luca-medeiros/lightning-sam#10]
Thanks for the exciting work. I have a question about your evaluation of the original SAM, based on what on your code have you calculated the F1 and IoU, or have you tried some prompts and then calculated the average?

**Comment by luca-medeiros** [comment]
Both original and finetuned models were calculated with https://github.com/luca-medeiros/lightning-sam/blob/80ac78866afa8ffc2f78ec2c314258b100589df0/lightning_sam/train.py#L23
I used bbox prompts for both.
Thanks for checking it out
