### ISSUE TITLE
suggestion for adjusting hyper-params in config.py

### ISSUE THREAD

**Issue by wiekern** [luca-medeiros/lightning-sam#12]
Hi, could you give some suggestions of adjusting  the hyper-params below in config.py.
```
"learning_rate": 2e-4,
"weight_decay": 3e-2,
"decay_factor": 10,
"steps": [2000, 4000],
"warmup_steps": 500,
```
Since the size of dataset varies amoung us, the smaller the dataset or the biggerthe batch size, the less the steps, so the default config of steps and warup_steps need to be modified. It would be nice if you could give any suggestion to adjust these params, thanks a lot!

**Comment by worklikerlei** [comment]
> Hi, could you give some suggestions of adjusting the hyper-params below in config.py.
> 
> ```
> "learning_rate": 2e-4,
> "weight_decay": 3e-2,
> "decay_factor": 10,
> "steps": [2000, 4000],
> "warmup_steps": 500,
> ```
> 
> Since the size of dataset varies amoung us, the smaller the dataset or the biggerthe batch size, the less the steps, so the default config of steps and warup_steps need to be modified. It would be nice if you could give any suggestion to adjust these params, thanks a lot!

hello, May I ask if you have encountered this error during the training process: RuntimeError: GET was unable to find an engine to execute this calculation, I feel that this error is caused by torch version=2.0. Is your torch version also 2.0.
Thank you very much!
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/57401869/236616142-9115a49f-9b00-40c2-8a1e-5ff98fd28df9.png">

**Comment by wiekern** [comment]
> > Hi, could you give some suggestions of adjusting the hyper-params below in config.py.
> > ```
> > "learning_rate": 2e-4,
> > "weight_decay": 3e-2,
> > "decay_factor": 10,
> > "steps": [2000, 4000],
> > "warmup_steps": 500,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since the size of dataset varies amoung us, the smaller the dataset or the biggerthe batch size, the less the steps, so the default config of steps and warup_steps need to be modified. It would be nice if you could give any suggestion to adjust these params, thanks a lot!
> 
> hello, May I ask if you have encountered this error during the training process: RuntimeError: GET was unable to find an engine to execute this calculation, I feel that this error is caused by torch version=2.0. Is your torch version also 2.0. Thank you very much! <img alt="image" width="1336" src="https://user-images.githubusercontent.com/57401869/236616142-9115a49f-9b00-40c2-8a1e-5ff98fd28df9.png">

torch 2.0
python 3.9
cuda 11.3 (nvcc --version)
highest cuda version supported by GPU driver: 11.7 ( nvidia-smi)

**Comment by luca-medeiros** [comment]
The procedure for training can be found in the original SAM paper. There they talk about the steps
