### ISSUE TITLE
No effect after fine-tuning

### ISSUE THREAD

**Issue by Bigtuo** [luca-medeiros/lightning-sam#26]
Nothing is recognized after fine-tuning

**Comment by skyfallsss** [comment]
I met the same problem

**Comment by Shivansh-Srivastava-techolution** [comment]
Even I tried it out the output deteriorates after training with each epoch

**Comment by luca-medeiros** [comment]
It needs to be used with bbox prompting.

**Comment by skyfallsss** [comment]
How to use  bbox prompting for segmenting?
