### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by othytrigui** [luca-medeiros/lightning-sam#30]
First of all, thanks for providing this code.
After fine-tuning the model and having the checkpoints saved, how can I use that checkpoint to test it on some images? to see if the model is performing well on new images.
Thanks again.

**Comment by yao-yu1999** [comment]
I also want to know about this issue.

**Comment by luca-medeiros** [comment]
You can use this 
https://github.com/luca-medeiros/lightning-sam/blob/58335bbd322c488862d6b961b9182a297a9358fd/lightning_sam/utils.py#L52 and add checkpoint loading

**Comment by YunyaGaoTree** [comment]
> 

Thanks so much for your answer.
By running this line, I can get predicted masks over images.

!python lightning_sam/utils.py

I also created a config file (config_test.py) specifically for this testing purpose.
Just need to change the "from config import cfg" to "from config_val import cfg".
Also, change the path of saved models or other parameters.

**Comment by Taoqi0402** [comment]
> > 
> 
> Thanks so much for your answer. By running this line, I can get predicted masks over images.
> 
> !python lightning_sam/utils.py
> 
> I also created a config file (config_test.py) specifically for this testing purpose. Just need to change the "from config import cfg" to "from config_val import cfg". Also, change the path of saved models or other parameters.

may I ask where to load the add check
