### ISSUE TITLE
how to train SamAutomaticMaskGenerator

### ISSUE THREAD

**Issue by moliniao** [luca-medeiros/lightning-sam#33]
First of all, thanks for providing such an elegant code.
if i need training  SamAutomaticMaskGenerator， Do you have any suggestions?

**Comment by YunyaGaoTree** [comment]
I met a problem when using SamAutomaticMaskGenerator to predict masks by using fine-tuned SAM models. It always returns an empty list. Look forward to answers.

**Comment by luca-medeiros** [comment]
Duplicate #38
