### ISSUE TITLE
error about requested gpu: [0, 1, 2, 3]

### ISSUE THREAD

**Issue by Imangnm** [luca-medeiros/lightning-sam#42]
I am trying to finetune SAM. but I get this error :
lightning.fabric.utilities.exceptions.MisconfigurationException: You requested gpu: [0, 1, 2, 3]
 But your machine only has: [0]
Does anybody know how can I solve it?

**Comment by luca-medeiros** [comment]
https://github.com/luca-medeiros/lightning-sam/blob/58335bbd322c488862d6b961b9182a297a9358fd/lightning_sam/config.py#L4
config is set for 4 gpus but your machine has only one.
